'use strict';

// new appContainer()
module.exports = function() {
  return {
    apps: [],
    // A koaApp is generated by calling koa() which creates a Koa server app instance
    init: function(koaApp) {
      this.koaApp = koaApp;
      this.routes = this.routes.init(this.koaApp);
      this.mount = this.mounter(this);
      return this;
    },
    start: function(koaApp) {
      if (koaApp) this.init(koaApp);
      this.koaApp.koaServer.start();
      return this;
    },
    mounter: require('./mounter'),
    routes: require('./routes')
  };
}
